### ISSUE TITLE
How to back up the whole Continuous integration system?

### ISSUE THREAD

**Issue by ghost** [openfrontier/ci#9]
Hi 
How to backup/restore the whole Continuous integration system?
Especially Jenkins, Gerrit.

**Comment by thinkernel** [comment]
Since our environment is running in a VM, I've never thought about that(we backup the VM instead).
Anyway, [there](https://docs.docker.com/v1.10/engine/userguide/containers/dockervolumes/#backup-restore-or-migrate-data-volumes) is a good reference about how to backup up a docker volume.
Volumes in these dockers should be backup: redmine-volume, jenkins-volume, gerrit-volume, nexus-volume, pg-redmine, pg-gerrit
I think that writing a backup script might be a good idea.

**Comment by ghost** [comment]
thank you very much.

> docker run --rm --volumes-from dbstore -v $(pwd):/backup ubuntu tar cvf /backup/backup.tar /dbdata
> For these data volumes, what are the folder  I should back up?
> e.x.
>     jenkins-volume:
>         docker run --rm --volumes-from jenkins-volume -v $(pwd):/backup busybox tar cvf /backup/jenkins.tar **/var/jenkins_home**
>     gerrit-volume:
>         docker run --rm --volumes-from gerrit-volume -v $(pwd):/backup busybox tar cvf /backup/gerrit.tar **/var/gerrit/review_site**
> redmine-volume:
>     docker run --rm --volumes-from redmine -v $(pwd):/backup busybox tar cvf /backup/redmine.tar **/home/redmine/data**
> pg-redmine:
>     docker run --rm --volumes-from pg-redmine -v $(pwd):/backup busybox tar cvf /backup/pg-redmine.tar /var/lib/postgresql/data
> pg-gerrit:
>     docker run --rm --volumes-from pg-gerrit -v $(pwd):/backup busybox tar cvf /backup/pg-gerrit.tar **/var/lib/postgresql/data**
> openldap-volume:
>     ?
> nexus-volume:
>     ?

**Comment by thinkernel** [comment]
`docker inspect -f '{{range $key, $value := .Config.Volumes}}{{printf "%s:%s\n" $key $value}}{{end}}' openldap-volume`
`docker inspect -f '{{range $key, $value := .Config.Volumes}}{{printf "%s:%s\n" $key $value}}{{end}}' nexus-volume`
These command will list the path of volumes for you.

**Comment by ghost** [comment]
Host1:
#Backup data volumes
#nexus-volume

# docker run --rm --volumes-from nexus-volume **-v /home/apps/backup:/backup busybox tar cvf /backup/nexus.tar /sonatype-work**

# **scp nexus.tar Host2:/home/apps/backup/**

Host2:
#Restore 

# ls -al /home/apps/backup/nexus.tar

-rw-r--r--. 1 root root 2066432 6月  29 21:31 /home/apps/backup/nexus.tar

# vi ~/nexus-docker/createNexus.sh

#####################################
#Start nexus
docker run \
--name ${NEXUS_NAME} \
-p 8081:8081 \
--volumes-from ${NEXUS_VOLUME} \
-e CONTEXT_PATH=/nexus \
**-v /home/apps/backup:/backup \**
-d ${NEXUS_IMAGE_NAME} \
**bash -c "cd / && tar xvf /backup/nexus.tar"**
#####################################

# ~/ci/run.sh

**................
Error response from daemon: Cannot start container 21a9f2690bc6316e18a3df0b2d01571de842a69af4f8924fdb3d54043b560505: Cannot link to a non running container: /nexus AS /proxy/nexus**

# docker logs nexus

sonatype-work/
sonatype-work/.java/
..................
sonatype-work/logs/nexus.log.2016-06-27.gz
sonatype-work/logs/nexus.log.2016-06-21.gz
sonatype-work/health-check/
#
The whole system can not run。。。。

**Comment by thinkernel** [comment]
You must create a nexus-volume container before running createNexus.sh.
Use script like this to create a volume container.

```
#!/bin/bash
set -e
NEXUS_NAME=${NEXUS_NAME:-nexus}
NEXUS_VOLUME=${NEXUS_VOLUME:-nexus-volume}
NEXUS_IMAGE_NAME=${NEXUS_IMAGE_NAME:-openfrontier/nexus}

#Create nexus volume.
if [ -z "$(docker ps -a | grep ${NEXUS_VOLUME})" ]; then
docker run \
--name ${NEXUS_VOLUME} \
${NEXUS_IMAGE_NAME} \
echo "Create nexus volume."
fi
```

Then uncompress the archive into the container by script like this one.
`docker run --volumes-from=nexus-volume -v $(pwd):/backup centos tar xvf /backup/nexus-volume.tar`

After that don't use createNexus.sh. Use upgradeNexus.sh instead.
I know it's ugly. But it's all I can help right now. I may write some backup and restore scripts when I'm available on it.

**Comment by thinkernel** [comment]
You must also backup the ssh key which is located at `~/.ssh/id_rsa` by default and you can change the location by specify SSH_KEY_PATH in the`~/ci/config` file.

**Comment by ghost** [comment]
Host1:
**#Backup data volumes and copy tar file to Host2**

```
cd /home/apps/backup
#nexus-volume
docker run --rm --volumes-from nexus-volume -v $(pwd):/backup busybox tar cvf /backup/nexus.tar /sonatype-work

#pg-gerrit
docker run --rm --volumes-from pg-gerrit -v $(pwd):/backup busybox tar cvf /backup/pg-gerrit.tar /var/lib/postgresql/data

#gerrit-volume
docker run --rm --volumes-from gerrit-volume -v $(pwd):/backup busybox tar cvf /backup/gerrit.tar /var/gerrit/review_site

#jenkins-volume
docker run --rm --volumes-from jenkins-volume -v $(pwd):/backup busybox tar cvf /backup/jenkins.tar /var/jenkins_home
```

**Host2:
#Restore data volumes**

```
1.Create
~/ci/run.sh

2.Then un-tar the backup file in the container’s data volume.
cd /home/apps/backup
#nexus-volume
docker run --rm --volumes-from nexus-volume -v $(pwd):/backup busybox tar xvf /backup/nexus.tar

#pg-gerrit
docker run --rm --volumes-from pg-gerrit -v $(pwd):/backup busybox tar xvf /backup/pg-gerrit.tar

#gerrit-volume
docker run --rm --volumes-from gerrit-volume -v $(pwd):/backup busybox tar xvf /backup/gerrit.tar

#jenkins-volume
docker run --rm --volumes-from jenkins-volume -v $(pwd):/backup busybox tar xvf /backup/jenkins.tar

3.vi ~/ci/upgradeContainer.sh
add code as follow:
##############################
# Create Nexus server.
if [ ${#NEXUS_WEBURL} -eq 0 ]; then
    source ~/nexus-docker/upgradeNexus.sh
fi
##############################

4. execute upgrade sehll
~/ci/upgradeContainer.sh

5.restart
~/ci/stop.sh

~/ci/start.sh
```

**But only nexus and jenkins  was restored, gerrit were not successful.
Although the data has been restored, but the UI pages are not displayed.**

**Comment by thinkernel** [comment]
Since openldap is not restored, I can see gerrit may not run properly. But Jenkins should be running because it doesn't depend on the openldap.
Can you show me the echo of this command? `docker logs jenkins`

**Comment by thinkernel** [comment]
Try these commands instead.
`docker run --rm --volumes-from pg-gerrit -v $(pwd):/backup busybox rm -rf /var/lib/postgresql/data/* && tar xvf /backup/pg-gerrit.tar`
`docker run --rm --volumes-from pg-gerrit -v $(pwd):/backup busybox rm -rf /var/gerrit/review_site/* && tar xvf /backup/pg-gerrit.tar`
`docker run --rm --volumes-from jenkins-volume -v $(pwd):/backup busybox rm -rf /var/jenkins_home/* && tar xvf /backup/jenkins.tar`
You must clean up the volumes before restore data into them.

**Comment by ghost** [comment]
I tried it again.
1.nexus and jenkins:ok
2.gerrit:ng
gerrit were not successful.
Although the data has been restored, but the UI pages are not displayed.
**docker logs gerrit**

```
[2016-06-30 16:41:31,396] [HTTP-57] WARN  com.google.gerrit.server.IdentifiedUser : Cannot query starred by user changes
com.google.gwtorm.server.OrmException: fetch failure on starred_changes
        at com.google.gwtorm.schema.sql.SqlDialect.convertError(SqlDialect.java:160)
        at com.google.gwtorm.schema.sql.DialectPostgreSQL.convertError(DialectPostgreSQL.java:65)
        at com.google.gwtorm.jdbc.JdbcAccess.convertError(JdbcAccess.java:466)
        at com.google.gwtorm.jdbc.JdbcAccess.queryList(JdbcAccess.java:157)
        at com.google.gerrit.reviewdb.client.StarredChange_Access_starredChanges_GwtOrm$$17.byAccount(Unknown Source)
        at com.google.gerrit.server.IdentifiedUser.starredQuery(IdentifiedUser.java:375)
        at com.google.gerrit.server.IdentifiedUser.asyncStarredChanges(IdentifiedUser.java:349)
        at com.google.gerrit.server.query.change.QueryChanges.query(QueryChanges.java:131)
        at com.google.gerrit.server.query.change.QueryChanges.apply(QueryChanges.java:99)
        at com.google.gerrit.server.query.change.QueryChanges.apply(QueryChanges.java:40)
        at com.google.gerrit.httpd.restapi.RestApiServlet.service(RestApiServlet.java:322)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at com.google.gerrit.httpd.GetUserFilter.doFilter(GetUserFilter.java:82)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:73)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:117)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:136)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:138)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:75)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
        at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: ERROR: index "starred_changes_pkey" contains corrupted page at block 0
  Hint: Please REINDEX it.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2103)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:273)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
        at com.google.gwtorm.jdbc.JdbcAccess.queryList(JdbcAccess.java:145)
        ... 45 more
```

in addition this file(~/openldap-docker/upgradeOpenLDAP.sh)  does not exist, 
can you provide it。

**Comment by thinkernel** [comment]
Added.

**Comment by ghost** [comment]
Thank you.
I didn't find the file. Can you tell me where it is？

**Comment by thinkernel** [comment]
Sorry. I forgot to push to remote. Check again, please.

**Comment by ghost** [comment]
Host1:
#Backup data volumes and copy tar file to Host2

```
cd /home/apps/backup
#Backup data volumes
#nexus-volume
docker run --rm --volumes-from nexus-volume -v $(pwd):/backup busybox tar cvf /backup/nexus.tar /sonatype-work
#openldap-volume
docker run --rm --volumes-from openldap-volume -v $(pwd):/backup busybox tar cvf /backup/openldap.tar /etc/ldap /var/lib/ldap
#pg-gerrit
docker run --rm --volumes-from pg-gerrit -v $(pwd):/backup busybox tar cvf /backup/pg-gerrit.tar /var/lib/postgresql/data
#gerrit-volume
docker run --rm --volumes-from gerrit-volume -v $(pwd):/backup busybox tar cvf /backup/gerrit.tar /var/gerrit/review_site
#jenkins-volume
docker run --rm --volumes-from jenkins-volume -v $(pwd):/backup busybox tar cvf /backup/jenkins.tar /var/jenkins_home
#pg-redmine
docker run --rm --volumes-from pg-redmine -v $(pwd):/backup busybox tar cvf /backup/pg-redmine.tar /var/lib/postgresql/data
#redmine-volume
docker run --rm --volumes-from redmine -v $(pwd):/backup busybox tar cvf /backup/redmine.tar /home/redmine/data /var/log/redmine

```

Host2:
#Restore data volumes

```
#1.Create
~/ci/run.sh

#Restore data volumes
cd /home/apps/backup
#nexus-volume
docker run --rm --volumes-from nexus-volume -v $(pwd):/backup busybox rm -rf /sonatype-work/*
docker run --rm --volumes-from nexus-volume -v $(pwd):/backup busybox tar xvf /backup/nexus.tar
#openldap-volume
docker run --rm --volumes-from openldap-volume -v $(pwd):/backup busybox rm -rf /etc/ldap/*
docker run --rm --volumes-from openldap-volume -v $(pwd):/backup busybox rm -rf /var/lib/ldap/*
docker run --rm --volumes-from openldap-volume -v $(pwd):/backup busybox tar xvf /backup/openldap.tar
#pg-gerrit
#docker run --rm --volumes-from pg-gerrit -v $(pwd):/backup busybox tar xvf /backup/pg-gerrit.tar
docker run --rm --volumes-from pg-gerrit -v $(pwd):/backup busybox rm -rf /var/lib/postgresql/data/*
docker run --rm --volumes-from pg-gerrit -v $(pwd):/backup busybox tar xvf /backup/pg-gerrit.tar
#gerrit-volume
docker run --rm --volumes-from gerrit-volume -v $(pwd):/backup busybox tar xvf /backup/gerrit.tar
docker run --rm --volumes-from gerrit-volume -v $(pwd):/backup busybox rm -rf /var/gerrit/review_site/*
docker run --rm --volumes-from gerrit-volume -v $(pwd):/backup busybox tar xvf /backup/gerrit.tar
#jenkins-volume
#docker run --rm --volumes-from jenkins-volume -v $(pwd):/backup busybox tar xvf /backup/jenkins.tar
docker run --rm --volumes-from jenkins-volume -v $(pwd):/backup busybox rm -rf /var/jenkins_home/*
docker run --rm --volumes-from jenkins-volume -v $(pwd):/backup busybox tar xvf /backup/jenkins.tar
#pg-redmine
docker run --rm --volumes-from redmine -v $(pwd):/backup busybox rm -rf /var/lib/postgresql/data/*
docker run --rm --volumes-from pg-redmine -v $(pwd):/backup busybox tar xvf /backup/pg-redmine.tar
#redmine-volume
docker run --rm --volumes-from redmine -v $(pwd):/backup busybox rm -rf /home/redmine/data/*
docker run --rm --volumes-from redmine -v $(pwd):/backup busybox rm -rf /var/log/redmine/*
docker run --rm --volumes-from redmine -v $(pwd):/backup busybox tar xvf /backup/redmine.tar

#3.upgrade
~/ci/upgradeContainer.sh
```

**Result：
The following Server has been restored
    nexus,openldap,jenkins

The following Server has not been restored
   gerrit:This directory(/var/gerrit/review_site) has been restored, but the UI Pageis only demo and demo-docker two projects。（_all Users has been restored_）

   redmine:Can not determine the directory has not been restored。（_all Users has not been restored_）**

**Comment by thinkernel** [comment]
Can you try adding ~/ci/stop.sh between ~/ci/run.sh and restore data?

**Comment by ghost** [comment]
Steps:
$ ~/ci/recreate.sh
$ ~/ci/stop.sh
##2.Restore data volumes

```
cd /home/apps/backup
#nexus-volume
docker run --rm --volumes-from nexus-volume -v $(pwd):/backup busybox rm -rf /sonatype-work/*
docker run --rm --volumes-from nexus-volume -v $(pwd):/backup busybox tar xvf /backup/nexus.tar

#openldap-volume
docker run --rm --volumes-from openldap-volume -v $(pwd):/backup busybox rm -rf /etc/ldap/*
docker run --rm --volumes-from openldap-volume -v $(pwd):/backup busybox rm -rf /var/lib/ldap/*
docker run --rm --volumes-from openldap-volume -v $(pwd):/backup busybox tar xvf /backup/openldap.tar

#pg-gerrit
docker run --rm --volumes-from pg-gerrit -v $(pwd):/backup busybox rm -rf /var/lib/postgresql/data/*
docker run --rm --volumes-from pg-gerrit -v $(pwd):/backup busybox tar xvf /backup/pg-gerrit.tar

#gerrit-volume
docker run --rm --volumes-from gerrit-volume -v $(pwd):/backup busybox rm -rf /var/gerrit/review_site/*
docker run --rm --volumes-from gerrit-volume -v $(pwd):/backup busybox tar xvf /backup/gerrit.tar

#jenkins-volume
docker run --rm --volumes-from jenkins-volume -v $(pwd):/backup busybox rm -rf /var/jenkins_home/*
docker run --rm --volumes-from jenkins-volume -v $(pwd):/backup busybox tar xvf /backup/jenkins.tar

#pg-redmine
docker run --rm --volumes-from redmine -v $(pwd):/backup busybox rm -rf /var/lib/postgresql/data/*
docker run --rm --volumes-from pg-redmine -v $(pwd):/backup busybox tar xvf /backup/pg-redmine.tar

#redmine-volume
docker run --rm --volumes-from redmine -v $(pwd):/backup busybox rm -rf /home/redmine/data/*
docker run --rm --volumes-from redmine -v $(pwd):/backup busybox rm -rf /var/log/redmine/*
docker run --rm --volumes-from redmine -v $(pwd):/backup busybox tar xvf /backup/redmine.tar

```

$ ~/ci/upgradeContainer.sh
**Has been restored to success.**
Thank you very much.

reference：

```
############################################
diff ~/ci/upgradeContainer.sh ~/ci/upgradeContainer.sh.bak
8,12d7
< # Create Nexus server.
< if [ ${#NEXUS_WEBURL} -eq 0 ]; then
<     source ~/nexus-docker/upgradeNexus.sh
< fi
<
14,16c9,11
< if [ ${#SLAPD_DOMAIN} -gt 0 -a ${#SLAPD_PASSWORD} -gt 0 ]; then
<     source ~/openldap-docker/upgradeOpenLDAP.sh
< fi
---
> #if [ ${#SLAPD_DOMAIN} -gt 0 -a ${#SLAPD_PASSWORD} -gt 0 ]; then
> #    source ~/openldap-docker/upgradeOpenLDAP.sh
> #fi
35c30
< source ~/redmine-docker/upgradeRedmine.sh
---
> #source ~/redmine-docker/upgradeRedmine.sh
37,40c32,35
< while [ -z "$(docker logs ${REDMINE_NAME} 2>&1 | tail -n 5 | grep 'INFO success: nginx entered RUNNING state')" ]; do
<     echo "Waiting redmine ready."
<     sleep 1
< done
---
> #while [ -z "$(docker logs ${REDMINE_NAME} 2>&1 | tail -n 5 | grep 'INFO success: nginx entered RUNNING state')" ]; do
> #    echo "Waiting redmine ready."
> #    sleep 1
> #done
############################################

```

```
############################################
diff ~/gerrit-docker/upgradeGerrit.sh ~/gerrit-docker/upgradeGerrit.sh.bak
30,32d29
< # Restart PostgreSQL.
< docker restart ${PG_GERRIT_NAME}
<
############################################
```

```
############################################
diff ~/redmine-docker/upgradeRedmine.sh ~/redmine-docker/upgradeRedmine.sh.bak
23,25d22
< # Restart PostgreSQL.
< docker restart ${PG_REDMINE_NAME}
<
############################################
```
